name: Bump Version Tag

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
     - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: make test
    - name: Bump version
      run: |
        git config --global user.email "treeder+actions@gmail.com"
        git config --global user.name "Actions"
        git fetch --tags
        wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash
